title: Nishant Mundhra's Portfolio
email: mundhranishant@gmail.com
logo: /assets/img/logo.png
description: "Insights driven by data, technology, and innovation."
show_downloads: true
url: "https://mundhranishant.github.io"
google_analytics:
theme: jekyll-theme-minimal
